// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// DynTable
List DynTable(NumericVector X, NumericVector Y, NumericVector sorted_x, NumericVector sorted_y, NumericVector slices_x, std::string method);
RcppExport SEXP _CFunStats_DynTable(SEXP XSEXP, SEXP YSEXP, SEXP sorted_xSEXP, SEXP sorted_ySEXP, SEXP slices_xSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sorted_x(sorted_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sorted_y(sorted_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type slices_x(slices_xSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(DynTable(X, Y, sorted_x, sorted_y, slices_x, method));
    return rcpp_result_gen;
END_RCPP
}
// tableRcpp
NumericMatrix tableRcpp(NumericVector x, NumericVector y, int xlevels, int ylevels);
RcppExport SEXP _CFunStats_tableRcpp(SEXP xSEXP, SEXP ySEXP, SEXP xlevelsSEXP, SEXP ylevelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type xlevels(xlevelsSEXP);
    Rcpp::traits::input_parameter< int >::type ylevels(ylevelsSEXP);
    rcpp_result_gen = Rcpp::wrap(tableRcpp(x, y, xlevels, ylevels));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CFunStats_DynTable", (DL_FUNC) &_CFunStats_DynTable, 6},
    {"_CFunStats_tableRcpp", (DL_FUNC) &_CFunStats_tableRcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_CFunStats(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
