# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DynTable <- function(X, Y, sorted_x, sorted_y, slices_x, method) {
    .Call('_CFunStats_DynTable', PACKAGE = 'CFunStats', X, Y, sorted_x, sorted_y, slices_x, method)
}

tableRcpp <- function(x, y, xlevels = -1L, ylevels = -1L) {
    .Call('_CFunStats_tableRcpp', PACKAGE = 'CFunStats', x, y, xlevels, ylevels)
}

